version = "1.4.3"

[releases."1.2.1"]
entries = ["patch-01khkj64ppmws0zfsp3jszp5dp.md"]

[releases."1.2.2"]
entries = ["patch-01khkkwqy6r24pj25k72bp5jec.md"]

[releases."1.3.0"]
entries = ["minor-01khkkxdphyqfypxya1vjrs94g.md"]

[releases."1.4.0"]
entries = ["minor-01khm51jhnzw66am1k2sqj3s5w.md"]

[releases."1.4.1"]
entries = ["patch-01khp50xsyd47awswyph8bwa31.md"]

[releases."1.4.2"]
entries = ["patch-01khv1ya5cxbd9av0mznpv3pe9.md"]

[releases."1.4.3"]
entries = ["patch-01kj38wz92k71p6cz1r85jgye0.md"]
