version = "1.4.1"

[releases."1.2.1"]
entries = ["patch-01khkj64ppmws0zfsp3jszp5dp.md"]

[releases."1.2.2"]
entries = ["patch-01khkkwqy6r24pj25k72bp5jec.md"]

[releases."1.3.0"]
entries = ["minor-01khkkxdphyqfypxya1vjrs94g.md"]

[releases."1.4.0"]
entries = ["minor-01khm51jhnzw66am1k2sqj3s5w.md"]

[releases."1.4.1"]
entries = ["patch-01khp50xsyd47awswyph8bwa31.md"]
